# Custom Models and Training with TensorFlow

In [21]:
import tensorflow as tf
import numpy as np


TensorFlow’s API revolves around tensors, which flow from operation to operation—hence the name TensorFlow. A tensor is usually a multidimensional array (exactly like a NumPy ndarray), but it can also hold a scalar (a simple value, such as 42).

## Using TensorFlow like NumPy

### Tensors and Operations

In [3]:
tf.constant([[1., 2., 3.], [4., 5., 6.]]) # matrix

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
tf.constant(42) # scalar

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [5]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t.shape, t.dtype

(TensorShape([2, 3]), tf.float32)

In [9]:
t[:, 2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 6.], dtype=float32)>

In [8]:
t[1:2, 2]

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([6.], dtype=float32)>

In [10]:
t + 16

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[17., 18., 19.],
       [20., 21., 22.]], dtype=float32)>

In [18]:
tf.add(t, 16)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[17., 18., 19.],
       [20., 21., 22.]], dtype=float32)>

In [11]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [12]:
tf.transpose(t)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [14]:
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [15]:
t @ tf.transpose(t) # dot multipication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [20]:
tf.matmul(t, tf.transpose(t)) # dot multipication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

Another operations available: 

        tf.add(), tf.multiply(), tf.square(), tf.exp(), tf.sqrt()  ...
        
        tf.reshape(), tf.squeeze(), tf.tile())  ...
        
        tf.reduce_mean(), tf.reduce_sum(), tf.reduce_max(), tf.math.log() - equivalents of np.mean(), np.sum(), np.max() and np.log(). 

### Tensors and NumPy

Tensors play nice with NumPy: you can create a tensor from a NumPy array, and vice versa. You can even apply TensorFlow operations to NumPy arrays and NumPy operations to tensors:

In [22]:
a = np.array([2., 4., 5.])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [23]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [24]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [25]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

### Converting Types

In [27]:
t2 = tf.constant(40, dtype=tf.float64)
t2

<tf.Tensor: shape=(), dtype=float64, numpy=40.0>

In [28]:
tf.constant(2.0)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [29]:
tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

### Variables

The tf.Tensor values are immutable: you cannot modify them. But tf.Variable values can be!

In [30]:
 tf.Variable([[1., 2., 3.], [4., 5., 6.]])

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [31]:
v =  tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v.assign(2 * v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [32]:
v[0, 1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [33]:
v.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[100., 200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   6.],
       [  8.,  10., 200.]], dtype=float32)>

### Strings

In [43]:
tf.constant("cafe")

<tf.Tensor: shape=(), dtype=string, numpy=b'cafe'>

In [38]:
tf.constant(b"notebook")

<tf.Tensor: shape=(), dtype=string, numpy=b'notebook'>

In [42]:
tf.constant("café")

<tf.Tensor: shape=(), dtype=string, numpy=b'caf\xc3\xa9'>